# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Hrushitha1234/Machine-Learning/blob/main/iris/iris.ipynb
"""

!git clone https://github.com/Hrushitha1234/Machine-Learning.git

import numpy as np
from pandas import read_csv
import sklearn
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

pip install scikit-learn

dataframe=read_csv("Machine-Learning/iris/iris.csv")
dataset=dataframe.values
data=dataset[:,0:4].astype(float)
labels=dataset[:,4]

(trainData,testData,trainLabels,testLabels)=train_test_split(np.array(data),np.array(labels),test_size=0.25,random_state=42)

"""Decision Trees"""

model=DecisionTreeClassifier(random_state=84)
print("[INFO] traning model..")
model.fit(trainData,trainLabels)
print("[INFO] evaluating...")
predictions=model.predict(testData)
print(classification_report(testLabels,predictions))

"""RandomForest"""

model=RandomForestClassifier(n_estimators=10,random_state=42,max_features="auto")
print("[INFO] traning model..")
model.fit(trainData,trainLabels)
print("[INFO] evaluating...")
predictions=model.predict(testData)
print(classification_report(testLabels,predictions))

"""KNN"""

model=KNeighborsClassifier(n_neighbors=9)
print("[INFO] traning model..")
model.fit(trainData,trainLabels)